# -*- coding: utf-8 -*-
"""Report content: per-actor whitepaper conformance mapping.
Each row: (whitepaper ref, requirement text, what was observed, evidence token, detail)
evidence tokens: chain | artifact | asserted | contra | fail | none
"""

MINER = [
 ("§3","A provider is a client_id inside a NO's miner pool, not a UID.",
  "Both epoch309 artifacts carry 8 providers each, identified by 16-byte client_id, with no subnet UID. The subnet's 256 UIDs hold 2 pool UIDs, 2 head UIDs and validators — never a tail provider.",
  "chain","artifact providers[].client_id; SubtensorModule::Keys census of all 256 UIDs"),
 ("§8.3","Providers claim α directly from the contract against their NO's committed payout root; the operator holds none of it.",
  "All 16 payments were transfers from the settlement vault to the provider coldkey. No operator address appears as a recipient. The vault is non-upgradeable.",
  "chain","16 ClaimPaid events; vault EIP-1967 implementation slot is zero"),
 ("§8.3","amount = s(n,p) · poolTotal(n), derived from immutable on-chain entitlement state.",
  "Every one of the 16 on-chain payment amounts was reproduced exactly as floor(share_bps × entitlement / 10 000) from the off-chain artifact leaf and the on-chain EntitlementFinalized total.",
  "chain","16/16 reproduced; see the settlement-chain figure"),
 ("§8.3","Release artifacts allocate exactly 10 000 bps with deterministic largest-remainder rounding.",
  "Each operator's 8 leaves sum to exactly 10 000 bps. The floor-rounding residues are 5 and 3 alpha-rao, summing to the 8 alpha-rao the contract reports as outstanding liability.",
  "chain","sum of leaf share_bps; residue reconciled against outstandingLiability()"),
 ("§8.3","Claimed records logical acceptance; ClaimPaid records the measured transfer; public history must not conflate them.",
  "Over the vault's entire lifetime there are 20 Claimed and 16 ClaimPaid. The 4 extra Claimed (epochs 296, 297) carry amount 0 — accepted entitlement against a zero pool total — and correctly emit no ClaimPaid and no ClaimPaymentDeferred.",
  "chain","complete vault log census, blocks 7,895,249 → head"),
 ("§11.2","A provider claims with a Merkle proof against the committed payout root.",
  "Both payout roots were rebuilt from the artifact leaves using an independent keccak-256 implementation and the OpenZeppelin double-hash sorted-pair scheme. Both match the root committed on chain. All 16 leaf proofs verify.",
  "chain","local Merkle rebuild; roots match OperatorRootCommitted"),
 ("§8.3","A pool cannot be over-drained: cumulative payout is capped at the entitlement total.",
  "Paid 103.320655346 α against 103.320655354 α captured; the 8 alpha-rao shortfall is floor-rounding residue, not overdraw. conservationHolds() returns true.",
  "chain","vault state at block 7,990,906"),
 ("§8.4","Top-level miners are steered directly by validators and paid natively — no contract custody, no Merkle claim.",
  "UIDs 7 and 8 received weight in all three applied vectors and never appear in any vault claim event. Their emission is native.",
  "chain","weight rows at 3 application blocks; vault claim census"),
]

VALIDATOR = [
 ("§5.1 / §10","Each tempo every independent validator scores every NO pool and submits under commit-reveal.",
  "commit_reveal_weights_enabled is true on netuid 521 with commit_reveal_period = 1 and tempo = 360. Three native weight extrinsics were located in their claimed blocks by BLAKE2b-256 hash.",
  "chain","runtime hyperparameters API; extrinsic hashing in blocks 7,986,181 / 7,987,311 / 7,987,774"),
 ("§10","normalize head so Σ head = θ; normalize pool so Σ pool = 1 − θ.",
  "The one applied vector carrying both channels (native 1404) splits head 0.29999947 / pool 0.70000053 against the governed θ = 3/10. Agreement to better than one part in 10⁶.",
  "chain","weight row at application block 7,987,601; pool UIDs from vault.pools()"),
 ("§10","Apply the signed policy max_weight_limit_u16, repairing rounding under the same cap.",
  "All three vectors respect the signed cap of 32 768. Native 1401 and 1405 land exactly on it (32 768), which is the cap-repair behaviour the spec describes.",
  "chain","normalized u16 of each weight row vs policy steering.max_weight_limit_u16"),
 ("§8.5","Policy empty_channel = cede_to_nonempty.",
  "In native 1401 and 1405 no pool UID appears at all; the head channel takes the whole vector. Both correspond to epochs with no eligible pool usage.",
  "chain","weight rows at blocks 7,986,519 and 7,988,052"),
 ("§9 / §3","Validators are independent Bittensor validator UIDs; weight-setting is decentralised across them.",
  "Only ONE UID (255) holds a weight row at every application block examined. The second validator never produced an applied weight vector before both exhausted their restart budgets. Yuma consensus, clipping and vtrust were therefore never exercised against a second independent scorer.",
  "fail","full 256-UID weight scan at all three application blocks"),
 ("§15.1","tempo 360, max_allowed_uids 256, min_allowed_weights 1, liquid_alpha_enabled true, immunity_period ≫ 4096 and > reveal interval.",
  "All hold live on netuid 521: tempo 360, max_allowed_uids 256, min_allowed_weights 1, liquid_alpha_enabled true, immunity_period 50 000 > 360.",
  "chain","subnetInfo_getSubnetHyperparamsV2 + direct storage reads"),
 ("§15.1","max_allowed_validators target ≤ 56 so ~200 miner slots fit.",
  "Live value is 64. The deployment's own compatibility gate records this as accepted for the bounded two-NO topology, with production governance required to lower it before targeting 200 head UIDs.",
  "contra","runtime hyperparameters API"),
 ("§7.4","The buyback reserve is α staked on the owner's validator hotkey, compounding.",
  "At finalized native block 7,992,355 the reserve hotkey at UID 254 holds 49 410.992336897 α of the 80 409.602927411 α across all 256 UIDs — 61.449 %. Above the 60 % configured minimum, below the 65 % repair target.",
  "chain","256-UID stake census decoded from raw Substrate storage; all 8 recorded queries replayed byte-identical"),
]

OPERATOR = [
 ("§3","A NO is a contract registration (noId) with one miner-pool UID, holding no emission.",
  "Two operators are registered on the coordinator, mapped to pool UIDs 3 and 4, owned by the immutable vault. Neither operator address received any α from the vault.",
  "chain","coordinator.operatorAt(); vault.pools(); full claim census"),
 ("§5.2","Each NO must commit its payout-list root for epoch e inside the root window.",
  "24 root commitments across 12 epochs — both operators every time. Every commitment landed 6 blocks after epoch end, inside the on-chain-enforced [end, end+50] window.",
  "chain","OperatorRootCommitted events vs epochEndBlock() + policy rootCommitWindowBlocks"),
 ("§5.2","coordinator.finalizeOperatorEpoch(e,n) opens the immutable entitlement after the finalize offset.",
  "24 entitlements finalized, each at end+153 blocks against the policy's +150 offset.",
  "chain","EntitlementFinalized events vs epochEndBlock() + finalizeOffsetBlocks"),
 ("§11.1","Committed roots and content-addressed payout artifacts are public and reproducible.",
  "Both epoch309 artifacts were retrieved through each operator's unauthenticated public API. Their content hashes recompute exactly from the canonical unsigned JSON and match the artifactHash committed on chain.",
  "chain","sha256 of canonical JSON; artifactHash in OperatorRootCommitted"),
 ("§8.2","The payout list is the NO's lever, but auditable.",
  "Shares are disclosed per leaf (8 leaves, 10 000 bps) with per-provider usage, assignments, confirmations and reliability_ppm, so a third party can re-derive the split from the artifact.",
  "artifact","artifact providers[] and leaves[]"),
 ("§11.1","The artifact is signed by the operator.",
  "Both signatures recover to their declared signers under local secp256k1 recovery. However, neither recovered signer is the coordinator-registered rootSigner for that operator — the artifact's embedded signature carries no authorisation the chain recognises. The on-chain binding is the artifactHash committed by the authorised rootSigner.",
  "contra","local ECDSA recovery vs coordinator.operatorAt().rootSigner"),
 ("§7.5","Deposits are published; the events are the record.",
  "10 Deposit events across epochs 298, 300, 305, 306 and 310, each carrying amount, policy hash and authorization nonce. Every amount cited in FINAL.md decodes exactly.",
  "chain","coordinator Deposit events"),
 ("§5.2 / §8.3","A missed root isolates to that operator's carry.",
  "67 RootMissed events. The epoch-308 miss is the consequential one: it is the only epoch that captured positive emission, and both operators missed it together. The value was not lost — it carried to epoch 309, which did commit roots — but the miss is a real operational failure, not a designed step.",
  "fail","RootMissed census; carry() trajectory"),
]

CONTRACT = [
 ("§8.3","poolTotal(n) = captured_emission(n) + same_operator_carry(n); a missed root carries to that same operator only.",
  "Epoch 308 captured 51,653,232,130 / 51,667,423,224 alpha-rao but no root was committed, so RootMissed(308) carried exactly those amounts at block 7,988,227. Epoch 309 captured zero, yet its entitlement was finalized at exactly the carried amounts. The vault's carry(noId) reads 0 before the miss, the full captured amount after it, and 0 again once the entitlement is fixed — with each operator's carry reaching only its own entitlement.",
  "chain","carry(1) and carry(2) read at four historical blocks; RootMissed and EntitlementFinalized payloads"),
 ("§6.4","Launch is centralised-but-bounded: an upgradeable policy coordinator, while the reserve and settlement vault are non-upgradeable from day one.",
  "The coordinator is an ERC-1967 proxy (130 bytes) upgraded 9 times. The settlement vault (9 797 bytes) and reserve sink (1 558 bytes) have a zero implementation slot and zero Upgraded events over their entire lifetime. Finalized claims are therefore not reachable by a coordinator upgrade.",
  "chain","EIP-1967 slot reads; full Upgraded event scan per contract"),
 ("§3","Three distinct mapped coldkeys: coordinator, immutable settlement vault, immutable reserve sink.",
  "All three addresses hold distinct code. vault.coordinator() resolves to the coordinator proxy; both are bound to netuid 521.",
  "chain","eth_getCode; vault.coordinator(); netuid() on both"),
 ("§6.3 / §8.3","The vault captures realized pool emission into immutable escrow and fixes an entitlement after the root window.",
  "48 EmissionCaptured and 24 EntitlementFinalized events. Exactly one epoch (308) captured a positive amount: 103.320655354 α. totalCaptured moved 0 → 103 320 655 354 in a single block and has not changed since.",
  "chain","complete vault log census + totalCaptured() trajectory"),
 ("§8.3","The contract computes no weight (D25); it custodies and settles only.",
  "The vault and coordinator ABIs expose no weight-setting entry point. All weight vectors on netuid 521 were submitted as native Substrate extrinsics by a validator hotkey, not by any contract.",
  "chain","contract ABI surface; native extrinsic authorship"),
 ("§5","Testnet acceptance uses a 360-block UR epoch, 60-block root window, 180-block finalize offset and 6-block close grace, and must complete three consecutive fully observed epochs.",
  "The chain has only ever carried two policy versions, both at 300 / 50 / 150 / 5 — the accelerated bootstrap cadence. The 360/60/180/6 production cadence was never scheduled. Measured epoch length over epochs 293–316 is exactly 300 blocks with a 150-block finalize offset.",
  "contra","coordinator policyCount() and policyByIndex(); 24-epoch measured cadence"),
 ("§6.4","A dedicated testnet key owns the coordinator; a pause-only guardian exists.",
  "One OwnershipTransferred and one GuardianSet event; paused() is false. Guardian and commitment-oracle changes are scheduled by epoch, as the staged-governance model requires.",
  "chain","coordinator event history; paused()"),
 ("§11.4","A fleet's client_ids are bound to a top-level miner's hotkey by a signed binding validators read.",
  "1 616 FleetBound and 800 FleetBindingRevoked events on the coordinator, plus 406 CommitmentMirrored — the binding and commitment-mirroring paths ran at real volume.",
  "chain","coordinator event census"),
 ("§8.3","An unclaimed remainder expires after the snapshotted TTL and becomes only that same NO's carry.",
  "claimTTLEpochs = 8, claimGraceEpochs = 1 in both policy versions; epoch309 entitlements carried expiry block 7,991,073 and all 16 claims landed before it. The expiry path itself was therefore never exercised.",
  "none","policy read; claim block heights vs expiryBlock"),
]
